// Code generated by ndpgen. DO NOT EDIT.
//
// This file provides stub implementations for non-WASM platforms.
// It allows Go plugins to compile and run tests outside of WASM,
// but the actual functionality is only available in WASM builds.
//
//go:build !wasip1

package mediaMarkerProvider

import "github.com/navidrome/navidrome/plugins/pdk/go/types"

// Deprecated: use types.ArtistRef.
type ArtistRef = types.ArtistRef

// GetMediaMarkersRequest contains the track information markers are requested for.
type GetMediaMarkersRequest struct {
	Track TrackInfo `json:"track"`
}

// GetMediaMarkersResponse contains the markers found by the plugin, if any.
type GetMediaMarkersResponse struct {
	Markers []MediaMarkerInfo `json:"markers"`
}

// MediaMarkerInfo is a single time-coded marker returned by a plugin. Kind is an open,
// namespaced string (e.g. "skip/lead_silence", "sample/amen-break"), not a fixed enum — see
// the media-time-markers repo's KINDS.md for the registry. EndMs is omitted for a point-in-time
// marker (e.g. "sample/wilhelm-scream") rather than a span.
type MediaMarkerInfo struct {
	// Kind is the marker's namespaced type, e.g. "skip/lead_silence".
	Kind string `json:"kind"`
	// StartMs is the marker's start offset in milliseconds.
	StartMs int64 `json:"startMs"`
	// EndMs is the marker's end offset in milliseconds. Omitted for a point-in-time marker.
	EndMs int64 `json:"endMs,omitempty"`
	// Confidence is an optional 0-1 score for anything auto-detected or community-sourced.
	Confidence float32 `json:"confidence,omitempty"`
}

// TrackInfo contains track metadata.
type TrackInfo struct {
	// ID is the internal Navidrome track ID.
	ID string `json:"id"`
	// Title is the track title.
	Title string `json:"title"`
	// Album is the album name.
	Album string `json:"album"`
	// Artist is the formatted artist name for display (e.g., "Artist1 • Artist2").
	Artist string `json:"artist"`
	// AlbumArtist is the formatted album artist name for display.
	AlbumArtist string `json:"albumArtist"`
	// Artists is the list of track artists.
	Artists []types.ArtistRef `json:"artists"`
	// AlbumArtists is the list of album artists.
	AlbumArtists []types.ArtistRef `json:"albumArtists"`
	// Duration is the track duration in seconds.
	Duration float32 `json:"duration"`
	// TrackNumber is the track number on the album.
	TrackNumber int32 `json:"trackNumber"`
	// DiscNumber is the disc number.
	DiscNumber int32 `json:"discNumber"`
	// MBZRecordingID is the MusicBrainz recording ID.
	MBZRecordingID string `json:"mbzRecordingId,omitempty"`
	// MBZAlbumID is the MusicBrainz album/release ID.
	MBZAlbumID string `json:"mbzAlbumId,omitempty"`
	// MBZReleaseGroupID is the MusicBrainz release group ID.
	MBZReleaseGroupID string `json:"mbzReleaseGroupId,omitempty"`
	// MBZReleaseTrackID is the MusicBrainz release track ID.
	MBZReleaseTrackID string `json:"mbzReleaseTrackId,omitempty"`
	// LibraryID is the ID of the library the track belongs to.
	// Only included if the plugin has library permission with filesystem access for the track's library.
	LibraryID int32 `json:"libraryId,omitempty"`
	// Path is the full path to the track file, relative to the library root.
	// Only included if the plugin has library permission with filesystem access for the track's library.
	Path string `json:"path,omitempty"`
}

// MediaMarkerProvider requires all methods to be implemented.
// MediaMarkerProvider supplies time-coded markers for a track — e.g. a spoken intro, or
// lead/trail silence around a hidden track (see media_marker DB table). This is a pull model:
// Navidrome calls GetMediaMarkers for a track at scan time, the same way MetadataAgent methods
// are invoked, rather than the plugin pushing data on its own schedule.
//
// A single method, so this capability is required=true: a plugin implementing it must return
// GetMediaMarkersResponse (which may be empty when the plugin has nothing for this track).
type MediaMarkerProvider interface {
	// GetMediaMarkers - GetMediaMarkers returns any markers this plugin can find for the given track.
	GetMediaMarkers(GetMediaMarkersRequest) (GetMediaMarkersResponse, error)
}

// NotImplementedCode is the standard return code for unimplemented functions.
const NotImplementedCode int32 = -2

// Register is a no-op on non-WASM platforms.
// This stub allows code to compile outside of WASM.
func Register(_ MediaMarkerProvider) {}
