// Code generated by ndpgen. DO NOT EDIT.
//
// This file contains client wrappers for the SpeechMusicDetect host service.
// It is intended for use in Navidrome plugins built with extism-pdk.

use extism_pdk::*;
use serde::{Deserialize, Serialize};

/// SpeechMusicDetectRequest identifies the library-relative file to analyze.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SpeechMusicDetectRequest {
    pub library_id: i32,
    pub path: String,
}

/// SpeechMusicDetectResponse contains the labeled segments inaSpeechSegmenter found in the file,
/// in chronological order.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SpeechMusicDetectResponse {
    pub segments: Vec<SpeechMusicSegment>,
}

/// SpeechMusicSegment is a labeled span of a track, in milliseconds, as classified by
/// inaSpeechSegmenter. Label is one of "speech", "music", "noEnergy" (silence), or "noise".
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SpeechMusicSegment {
    pub label: String,
    pub start_ms: i64,
    pub end_ms: i64,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct SpeechMusicDetectDetectRequest {
    request: SpeechMusicDetectRequest,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
struct SpeechMusicDetectDetectResponse {
    #[serde(default)]
    result: Option<SpeechMusicDetectResponse>,
    #[serde(default)]
    error: Option<String>,
}

#[host_fn]
extern "ExtismHost" {
    fn speechmusicdetect_detect(input: Json<SpeechMusicDetectDetectRequest>) -> Json<SpeechMusicDetectDetectResponse>;
}

/// Detect runs inaSpeechSegmenter on the given library-relative file and returns its
/// labeled segments.
///
/// # Arguments
/// * `request` - SpeechMusicDetectRequest parameter.
///
/// # Returns
/// The result value.
///
/// # Errors
/// Returns an error if the host function call fails.
pub fn detect(request: SpeechMusicDetectRequest) -> Result<Option<SpeechMusicDetectResponse>, Error> {
    let response = unsafe {
        speechmusicdetect_detect(Json(SpeechMusicDetectDetectRequest {
            request: request,
        }))?
    };

    if let Some(err) = response.0.error {
        return Err(Error::msg(err));
    }

    Ok(response.0.result)
}
