// Code generated by ndpgen. DO NOT EDIT.
//
// This file contains client wrappers for the SilenceDetect host service.
// It is intended for use in Navidrome plugins built with extism-pdk.

use extism_pdk::*;
use serde::{Deserialize, Serialize};

/// SilenceDetectRequest identifies the library-relative file to analyze and the ffmpeg
/// silencedetect thresholds to use.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SilenceDetectRequest {
    pub library_id: i32,
    pub path: String,
    #[serde(default)]
    pub noise_db: f32,
    #[serde(default)]
    pub duration_ms: i32,
}

/// SilenceDetectResponse contains the spans of silence ffmpeg found in the file.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SilenceDetectResponse {
    pub spans: Vec<SilenceSpan>,
}

/// SilenceSpan is a detected span of silence within a track, in milliseconds.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SilenceSpan {
    pub start_ms: i64,
    pub end_ms: i64,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct SilenceDetectDetectRequest {
    request: SilenceDetectRequest,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
struct SilenceDetectDetectResponse {
    #[serde(default)]
    result: Option<SilenceDetectResponse>,
    #[serde(default)]
    error: Option<String>,
}

#[host_fn]
extern "ExtismHost" {
    fn silencedetect_detect(input: Json<SilenceDetectDetectRequest>) -> Json<SilenceDetectDetectResponse>;
}

/// Detect runs ffmpeg silencedetect on the given library-relative file and returns the
/// detected silence spans.
///
/// # Arguments
/// * `request` - SilenceDetectRequest parameter.
///
/// # Returns
/// The result value.
///
/// # Errors
/// Returns an error if the host function call fails.
pub fn detect(request: SilenceDetectRequest) -> Result<Option<SilenceDetectResponse>, Error> {
    let response = unsafe {
        silencedetect_detect(Json(SilenceDetectDetectRequest {
            request: request,
        }))?
    };

    if let Some(err) = response.0.error {
        return Err(Error::msg(err));
    }

    Ok(response.0.result)
}
