// Code generated by ndpgen. DO NOT EDIT.
//
// This file contains client wrappers for the Fingerprint host service.
// It is intended for use in Navidrome plugins built with extism-pdk.

use extism_pdk::*;
use serde::{Deserialize, Serialize};

/// FingerprintRequest identifies the library-relative file to fingerprint.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FingerprintRequest {
    pub library_id: i32,
    pub path: String,
}

/// FingerprintResponse contains the computed Chromaprint fingerprint.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FingerprintResponse {
    pub fingerprint: String,
    pub duration_ms: i64,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct FingerprintComputeRequest {
    request: FingerprintRequest,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
struct FingerprintComputeResponse {
    #[serde(default)]
    result: Option<FingerprintResponse>,
    #[serde(default)]
    error: Option<String>,
}

#[host_fn]
extern "ExtismHost" {
    fn fingerprint_compute(input: Json<FingerprintComputeRequest>) -> Json<FingerprintComputeResponse>;
}

/// Compute runs fpcalc on the given library-relative file and returns its fingerprint.
///
/// # Arguments
/// * `request` - FingerprintRequest parameter.
///
/// # Returns
/// The result value.
///
/// # Errors
/// Returns an error if the host function call fails.
pub fn compute(request: FingerprintRequest) -> Result<Option<FingerprintResponse>, Error> {
    let response = unsafe {
        fingerprint_compute(Json(FingerprintComputeRequest {
            request: request,
        }))?
    };

    if let Some(err) = response.0.error {
        return Err(Error::msg(err));
    }

    Ok(response.0.result)
}
