// Code generated by ndpgen. DO NOT EDIT.
//
// This file contains export wrappers for the MediaMarkerProvider capability.
// It is intended for use in Navidrome plugins built with extism-pdk.

use serde::{Deserialize, Serialize};

// Helper functions for skip_serializing_if with numeric types
#[allow(dead_code)]
fn is_zero_i32(value: &i32) -> bool { *value == 0 }
#[allow(dead_code)]
fn is_zero_u32(value: &u32) -> bool { *value == 0 }
#[allow(dead_code)]
fn is_zero_i64(value: &i64) -> bool { *value == 0 }
#[allow(dead_code)]
fn is_zero_u64(value: &u64) -> bool { *value == 0 }
#[allow(dead_code)]
fn is_zero_f32(value: &f32) -> bool { *value == 0.0 }
#[allow(dead_code)]
fn is_zero_f64(value: &f64) -> bool { *value == 0.0 }

#[deprecated(note = "use nd_pdk::types::ArtistRef")]
pub type ArtistRef = nd_pdk_types::ArtistRef;
/// GetMediaMarkersRequest contains the track information markers are requested for.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetMediaMarkersRequest {
    #[serde(default)]
    pub track: TrackInfo,
}
/// GetMediaMarkersResponse contains the markers found by the plugin, if any.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetMediaMarkersResponse {
    #[serde(default)]
    pub markers: Vec<MediaMarkerInfo>,
}
/// MediaMarkerInfo is a single time-coded marker returned by a plugin. Kind is an open,
/// namespaced string (e.g. "skip/lead_silence", "sample/amen-break"), not a fixed enum — see
/// the media-time-markers repo's KINDS.md for the registry. EndMs is omitted for a point-in-time
/// marker (e.g. "sample/wilhelm-scream") rather than a span.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MediaMarkerInfo {
    /// Kind is the marker's namespaced type, e.g. "skip/lead_silence".
    #[serde(default)]
    pub kind: String,
    /// StartMs is the marker's start offset in milliseconds.
    #[serde(default)]
    pub start_ms: i64,
    /// EndMs is the marker's end offset in milliseconds. Omitted for a point-in-time marker.
    #[serde(default, skip_serializing_if = "is_zero_i64")]
    pub end_ms: i64,
    /// Confidence is an optional 0-1 score for anything auto-detected or community-sourced.
    #[serde(default, skip_serializing_if = "is_zero_f32")]
    pub confidence: f32,
}
/// TrackInfo contains track metadata.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TrackInfo {
    /// ID is the internal Navidrome track ID.
    #[serde(default)]
    pub id: String,
    /// Title is the track title.
    #[serde(default)]
    pub title: String,
    /// Album is the album name.
    #[serde(default)]
    pub album: String,
    /// Artist is the formatted artist name for display (e.g., "Artist1 • Artist2").
    #[serde(default)]
    pub artist: String,
    /// AlbumArtist is the formatted album artist name for display.
    #[serde(default)]
    pub album_artist: String,
    /// Artists is the list of track artists.
    #[serde(default)]
    pub artists: Vec<nd_pdk_types::ArtistRef>,
    /// AlbumArtists is the list of album artists.
    #[serde(default)]
    pub album_artists: Vec<nd_pdk_types::ArtistRef>,
    /// Duration is the track duration in seconds.
    #[serde(default)]
    pub duration: f32,
    /// TrackNumber is the track number on the album.
    #[serde(default)]
    pub track_number: i32,
    /// DiscNumber is the disc number.
    #[serde(default)]
    pub disc_number: i32,
    /// MBZRecordingID is the MusicBrainz recording ID.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub mbz_recording_id: String,
    /// MBZAlbumID is the MusicBrainz album/release ID.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub mbz_album_id: String,
    /// MBZReleaseGroupID is the MusicBrainz release group ID.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub mbz_release_group_id: String,
    /// MBZReleaseTrackID is the MusicBrainz release track ID.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub mbz_release_track_id: String,
    /// LibraryID is the ID of the library the track belongs to.
    /// Only included if the plugin has library permission with filesystem access for the track's library.
    #[serde(default, skip_serializing_if = "is_zero_i32")]
    pub library_id: i32,
    /// Path is the full path to the track file, relative to the library root.
    /// Only included if the plugin has library permission with filesystem access for the track's library.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub path: String,
}

/// Error represents an error from a capability method.
#[derive(Debug)]
pub struct Error {
    pub message: String,
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message)
    }
}

impl std::error::Error for Error {}

impl Error {
    pub fn new(message: impl Into<String>) -> Self {
        Self { message: message.into() }
    }
}

/// MediaMarkerProvider requires all methods to be implemented.
/// MediaMarkerProvider supplies time-coded markers for a track — e.g. a spoken intro, or
/// lead/trail silence around a hidden track (see media_marker DB table). This is a pull model:
/// Navidrome calls GetMediaMarkers for a track at scan time, the same way MetadataAgent methods
/// are invoked, rather than the plugin pushing data on its own schedule.
/// 
/// A single method, so this capability is required=true: a plugin implementing it must return
/// GetMediaMarkersResponse (which may be empty when the plugin has nothing for this track).
pub trait MediaMarkerProvider {
    /// GetMediaMarkers - GetMediaMarkers returns any markers this plugin can find for the given track.
    fn get_media_markers(&self, req: GetMediaMarkersRequest) -> Result<GetMediaMarkersResponse, Error>;
}

/// Register all exports for the MediaMarkerProvider capability.
/// This macro generates the WASM export functions for all trait methods.
#[macro_export]
macro_rules! register_media_marker_provider {
    ($plugin_type:ty) => {
        #[extism_pdk::plugin_fn]
        pub fn nd_get_media_markers(
            req: extism_pdk::Json<$crate::media_marker_provider::GetMediaMarkersRequest>
        ) -> extism_pdk::FnResult<extism_pdk::Json<$crate::media_marker_provider::GetMediaMarkersResponse>> {
            let plugin = <$plugin_type>::default();
            let result = $crate::media_marker_provider::MediaMarkerProvider::get_media_markers(&plugin, req.into_inner())?;
            Ok(extism_pdk::Json(result))
        }
    };
}
