// Code generated by ndpgen. DO NOT EDIT.

package host

import (
	"context"
	"encoding/json"

	extism "github.com/extism/go-sdk"
)

// FingerprintComputeRequest is the request type for Fingerprint.Compute.
type FingerprintComputeRequest struct {
	Request FingerprintRequest `json:"request"`
}

// FingerprintComputeResponse is the response type for Fingerprint.Compute.
type FingerprintComputeResponse struct {
	Result *FingerprintResponse `json:"result,omitempty"`
	Error  string               `json:"error,omitempty"`
}

// RegisterFingerprintHostFunctions registers Fingerprint service host functions.
// The returned host functions should be added to the plugin's configuration.
func RegisterFingerprintHostFunctions(service FingerprintService) []extism.HostFunction {
	return []extism.HostFunction{
		newFingerprintComputeHostFunction(service),
	}
}

func newFingerprintComputeHostFunction(service FingerprintService) extism.HostFunction {
	return extism.NewHostFunctionWithStack(
		"fingerprint_compute",
		func(ctx context.Context, p *extism.CurrentPlugin, stack []uint64) {
			// Read JSON request from plugin memory
			reqBytes, err := p.ReadBytes(stack[0])
			if err != nil {
				fingerprintWriteError(p, stack, err)
				return
			}
			var req FingerprintComputeRequest
			if err := json.Unmarshal(reqBytes, &req); err != nil {
				fingerprintWriteError(p, stack, err)
				return
			}

			// Call the service method
			result, svcErr := service.Compute(ctx, req.Request)
			if svcErr != nil {
				fingerprintWriteError(p, stack, svcErr)
				return
			}

			// Write JSON response to plugin memory
			resp := FingerprintComputeResponse{
				Result: result,
			}
			fingerprintWriteResponse(p, stack, resp)
		},
		[]extism.ValueType{extism.ValueTypePTR},
		[]extism.ValueType{extism.ValueTypePTR},
	)
}

// fingerprintWriteResponse writes a JSON response to plugin memory.
func fingerprintWriteResponse(p *extism.CurrentPlugin, stack []uint64, resp any) {
	respBytes, err := json.Marshal(resp)
	if err != nil {
		fingerprintWriteError(p, stack, err)
		return
	}
	respPtr, err := p.WriteBytes(respBytes)
	if err != nil {
		stack[0] = 0
		return
	}
	stack[0] = respPtr
}

// fingerprintWriteError writes an error response to plugin memory.
func fingerprintWriteError(p *extism.CurrentPlugin, stack []uint64, err error) {
	errResp := struct {
		Error string `json:"error"`
	}{Error: err.Error()}
	respBytes, _ := json.Marshal(errResp)
	respPtr, _ := p.WriteBytes(respBytes)
	stack[0] = respPtr
}
