// Code generated by ndpgen. DO NOT EDIT.

package host

import (
	"context"
	"encoding/json"

	extism "github.com/extism/go-sdk"
)

// SilenceDetectDetectRequest is the request type for SilenceDetect.Detect.
type SilenceDetectDetectRequest struct {
	Request SilenceDetectRequest `json:"request"`
}

// SilenceDetectDetectResponse is the response type for SilenceDetect.Detect.
type SilenceDetectDetectResponse struct {
	Result *SilenceDetectResponse `json:"result,omitempty"`
	Error  string                 `json:"error,omitempty"`
}

// RegisterSilenceDetectHostFunctions registers SilenceDetect service host functions.
// The returned host functions should be added to the plugin's configuration.
func RegisterSilenceDetectHostFunctions(service SilenceDetectService) []extism.HostFunction {
	return []extism.HostFunction{
		newSilenceDetectDetectHostFunction(service),
	}
}

func newSilenceDetectDetectHostFunction(service SilenceDetectService) extism.HostFunction {
	return extism.NewHostFunctionWithStack(
		"silencedetect_detect",
		func(ctx context.Context, p *extism.CurrentPlugin, stack []uint64) {
			// Read JSON request from plugin memory
			reqBytes, err := p.ReadBytes(stack[0])
			if err != nil {
				silencedetectWriteError(p, stack, err)
				return
			}
			var req SilenceDetectDetectRequest
			if err := json.Unmarshal(reqBytes, &req); err != nil {
				silencedetectWriteError(p, stack, err)
				return
			}

			// Call the service method
			result, svcErr := service.Detect(ctx, req.Request)
			if svcErr != nil {
				silencedetectWriteError(p, stack, svcErr)
				return
			}

			// Write JSON response to plugin memory
			resp := SilenceDetectDetectResponse{
				Result: result,
			}
			silencedetectWriteResponse(p, stack, resp)
		},
		[]extism.ValueType{extism.ValueTypePTR},
		[]extism.ValueType{extism.ValueTypePTR},
	)
}

// silencedetectWriteResponse writes a JSON response to plugin memory.
func silencedetectWriteResponse(p *extism.CurrentPlugin, stack []uint64, resp any) {
	respBytes, err := json.Marshal(resp)
	if err != nil {
		silencedetectWriteError(p, stack, err)
		return
	}
	respPtr, err := p.WriteBytes(respBytes)
	if err != nil {
		stack[0] = 0
		return
	}
	stack[0] = respPtr
}

// silencedetectWriteError writes an error response to plugin memory.
func silencedetectWriteError(p *extism.CurrentPlugin, stack []uint64, err error) {
	errResp := struct {
		Error string `json:"error"`
	}{Error: err.Error()}
	respBytes, _ := json.Marshal(errResp)
	respPtr, _ := p.WriteBytes(respBytes)
	stack[0] = respPtr
}
