// Code generated by ndpgen. DO NOT EDIT.

package host

import (
	"context"
	"encoding/json"

	extism "github.com/extism/go-sdk"
)

// SpeechMusicDetectDetectRequest is the request type for SpeechMusicDetect.Detect.
type SpeechMusicDetectDetectRequest struct {
	Request SpeechMusicDetectRequest `json:"request"`
}

// SpeechMusicDetectDetectResponse is the response type for SpeechMusicDetect.Detect.
type SpeechMusicDetectDetectResponse struct {
	Result *SpeechMusicDetectResponse `json:"result,omitempty"`
	Error  string                     `json:"error,omitempty"`
}

// RegisterSpeechMusicDetectHostFunctions registers SpeechMusicDetect service host functions.
// The returned host functions should be added to the plugin's configuration.
func RegisterSpeechMusicDetectHostFunctions(service SpeechMusicDetectService) []extism.HostFunction {
	return []extism.HostFunction{
		newSpeechMusicDetectDetectHostFunction(service),
	}
}

func newSpeechMusicDetectDetectHostFunction(service SpeechMusicDetectService) extism.HostFunction {
	return extism.NewHostFunctionWithStack(
		"speechmusicdetect_detect",
		func(ctx context.Context, p *extism.CurrentPlugin, stack []uint64) {
			// Read JSON request from plugin memory
			reqBytes, err := p.ReadBytes(stack[0])
			if err != nil {
				speechmusicdetectWriteError(p, stack, err)
				return
			}
			var req SpeechMusicDetectDetectRequest
			if err := json.Unmarshal(reqBytes, &req); err != nil {
				speechmusicdetectWriteError(p, stack, err)
				return
			}

			// Call the service method
			result, svcErr := service.Detect(ctx, req.Request)
			if svcErr != nil {
				speechmusicdetectWriteError(p, stack, svcErr)
				return
			}

			// Write JSON response to plugin memory
			resp := SpeechMusicDetectDetectResponse{
				Result: result,
			}
			speechmusicdetectWriteResponse(p, stack, resp)
		},
		[]extism.ValueType{extism.ValueTypePTR},
		[]extism.ValueType{extism.ValueTypePTR},
	)
}

// speechmusicdetectWriteResponse writes a JSON response to plugin memory.
func speechmusicdetectWriteResponse(p *extism.CurrentPlugin, stack []uint64, resp any) {
	respBytes, err := json.Marshal(resp)
	if err != nil {
		speechmusicdetectWriteError(p, stack, err)
		return
	}
	respPtr, err := p.WriteBytes(respBytes)
	if err != nil {
		stack[0] = 0
		return
	}
	stack[0] = respPtr
}

// speechmusicdetectWriteError writes an error response to plugin memory.
func speechmusicdetectWriteError(p *extism.CurrentPlugin, stack []uint64, err error) {
	errResp := struct {
		Error string `json:"error"`
	}{Error: err.Error()}
	respBytes, _ := json.Marshal(errResp)
	respPtr, _ := p.WriteBytes(respBytes)
	stack[0] = respPtr
}
