// Code generated by ndpgen. DO NOT EDIT.
//
// This file contains client wrappers for the Fingerprint host service.
// It is intended for use in Navidrome plugins built with TinyGo.
//
//go:build wasip1

package host

import (
	"encoding/json"
	"errors"

	"github.com/navidrome/navidrome/plugins/pdk/go/pdk"
)

// FingerprintRequest represents the FingerprintRequest data structure.
// FingerprintRequest identifies the library-relative file to fingerprint.
type FingerprintRequest struct {
	LibraryID int32  `json:"libraryId"`
	Path      string `json:"path"`
}

// FingerprintResponse represents the FingerprintResponse data structure.
// FingerprintResponse contains the computed Chromaprint fingerprint.
type FingerprintResponse struct {
	Fingerprint string `json:"fingerprint"`
	DurationMs  int64  `json:"durationMs"`
}

// fingerprint_compute is the host function provided by Navidrome.
//
//go:wasmimport extism:host/user fingerprint_compute
func fingerprint_compute(uint64) uint64

type fingerprintComputeRequest struct {
	Request FingerprintRequest `json:"request"`
}

type fingerprintComputeResponse struct {
	Result *FingerprintResponse `json:"result,omitempty"`
	Error  string               `json:"error,omitempty"`
}

// FingerprintCompute calls the fingerprint_compute host function.
// Compute runs fpcalc on the given library-relative file and returns its fingerprint.
func FingerprintCompute(request FingerprintRequest) (*FingerprintResponse, error) {
	// Marshal request to JSON
	req := fingerprintComputeRequest{
		Request: request,
	}
	reqBytes, err := json.Marshal(req)
	if err != nil {
		return nil, err
	}
	reqMem := pdk.AllocateBytes(reqBytes)
	defer reqMem.Free()

	// Call the host function
	responsePtr := fingerprint_compute(reqMem.Offset())

	// Read the response from memory
	responseMem := pdk.FindMemory(responsePtr)
	responseBytes := responseMem.ReadBytes()

	// Parse the response
	var response fingerprintComputeResponse
	if err := json.Unmarshal(responseBytes, &response); err != nil {
		return nil, err
	}

	// Convert Error field to Go error
	if response.Error != "" {
		return nil, errors.New(response.Error)
	}

	return response.Result, nil
}
