// Code generated by ndpgen. DO NOT EDIT.
//
// This file contains client wrappers for the SilenceDetect host service.
// It is intended for use in Navidrome plugins built with TinyGo.
//
//go:build wasip1

package host

import (
	"encoding/json"
	"errors"

	"github.com/navidrome/navidrome/plugins/pdk/go/pdk"
)

// SilenceDetectRequest represents the SilenceDetectRequest data structure.
// SilenceDetectRequest identifies the library-relative file to analyze and the ffmpeg
// silencedetect thresholds to use.
type SilenceDetectRequest struct {
	LibraryID  int32   `json:"libraryId"`
	Path       string  `json:"path"`
	NoiseDB    float32 `json:"noiseDb"`
	DurationMs int32   `json:"durationMs"`
}

// SilenceDetectResponse represents the SilenceDetectResponse data structure.
// SilenceDetectResponse contains the spans of silence ffmpeg found in the file.
type SilenceDetectResponse struct {
	Spans []SilenceSpan `json:"spans"`
}

// SilenceSpan represents the SilenceSpan data structure.
// SilenceSpan is a detected span of silence within a track, in milliseconds.
type SilenceSpan struct {
	StartMs int64 `json:"startMs"`
	EndMs   int64 `json:"endMs"`
}

// silencedetect_detect is the host function provided by Navidrome.
//
//go:wasmimport extism:host/user silencedetect_detect
func silencedetect_detect(uint64) uint64

type silenceDetectDetectRequest struct {
	Request SilenceDetectRequest `json:"request"`
}

type silenceDetectDetectResponse struct {
	Result *SilenceDetectResponse `json:"result,omitempty"`
	Error  string                 `json:"error,omitempty"`
}

// SilenceDetectDetect calls the silencedetect_detect host function.
// Detect runs ffmpeg silencedetect on the given library-relative file and returns the
// detected silence spans.
func SilenceDetectDetect(request SilenceDetectRequest) (*SilenceDetectResponse, error) {
	// Marshal request to JSON
	req := silenceDetectDetectRequest{
		Request: request,
	}
	reqBytes, err := json.Marshal(req)
	if err != nil {
		return nil, err
	}
	reqMem := pdk.AllocateBytes(reqBytes)
	defer reqMem.Free()

	// Call the host function
	responsePtr := silencedetect_detect(reqMem.Offset())

	// Read the response from memory
	responseMem := pdk.FindMemory(responsePtr)
	responseBytes := responseMem.ReadBytes()

	// Parse the response
	var response silenceDetectDetectResponse
	if err := json.Unmarshal(responseBytes, &response); err != nil {
		return nil, err
	}

	// Convert Error field to Go error
	if response.Error != "" {
		return nil, errors.New(response.Error)
	}

	return response.Result, nil
}
