// Code generated by ndpgen. DO NOT EDIT.
//
// This file contains mock implementations for non-WASM builds.
// These mocks allow IDE support, compilation, and unit testing on non-WASM platforms.
// Plugin authors can use the exported mock instances to set expectations in tests.
//
//go:build !wasip1

package host

import (
	"github.com/stretchr/testify/mock"
)

// SpeechMusicDetectRequest represents the SpeechMusicDetectRequest data structure.
// SpeechMusicDetectRequest identifies the library-relative file to analyze.
type SpeechMusicDetectRequest struct {
	LibraryID int32  `json:"libraryId"`
	Path      string `json:"path"`
}

// SpeechMusicDetectResponse represents the SpeechMusicDetectResponse data structure.
// SpeechMusicDetectResponse contains the labeled segments inaSpeechSegmenter found in the file,
// in chronological order.
type SpeechMusicDetectResponse struct {
	Segments []SpeechMusicSegment `json:"segments"`
}

// SpeechMusicSegment represents the SpeechMusicSegment data structure.
// SpeechMusicSegment is a labeled span of a track, in milliseconds, as classified by
// inaSpeechSegmenter. Label is one of "speech", "music", "noEnergy" (silence), or "noise".
//
// Window identifies which classified window this segment came from ("lead" or "trail") — the
// underlying classifier only ever looks at the leading/trailing few minutes of a track (see
// core/inaspeech/segment.py), not the whole thing, so a caller that needs a boundary within a
// single window (e.g. "where does the leading speech run end") must not search across both
// windows' segments as if they were one continuous timeline: there's a real time gap between
// them for any track longer than roughly 2x the window size, and after the classified audio is
// run through Demucs vocal separation, a "music" label essentially never appears at all (an
// isolated vocal stem has no music content to classify) — so any logic that used to scan for a
// music-labeled boundary across the full segment list needs to work per-window instead.
type SpeechMusicSegment struct {
	Label   string `json:"label"`
	StartMs int64  `json:"startMs"`
	EndMs   int64  `json:"endMs"`
	Window  string `json:"window"`
}

// mockSpeechMusicDetectService is the mock implementation for testing.
type mockSpeechMusicDetectService struct {
	mock.Mock
}

// SpeechMusicDetectMock is the auto-instantiated mock instance for testing.
// Use this to set expectations: host.SpeechMusicDetectMock.On("MethodName", args...).Return(values...)
var SpeechMusicDetectMock = &mockSpeechMusicDetectService{}

// Detect is the mock method for SpeechMusicDetectDetect.
func (m *mockSpeechMusicDetectService) Detect(request SpeechMusicDetectRequest) (*SpeechMusicDetectResponse, error) {
	args := m.Called(request)
	return args.Get(0).(*SpeechMusicDetectResponse), args.Error(1)
}

// SpeechMusicDetectDetect delegates to the mock instance.
// Detect runs inaSpeechSegmenter on the given library-relative file and returns its
// labeled segments.
func SpeechMusicDetectDetect(request SpeechMusicDetectRequest) (*SpeechMusicDetectResponse, error) {
	return SpeechMusicDetectMock.Detect(request)
}
