// Code generated by ndpgen. DO NOT EDIT.
//
// This file contains mock implementations for non-WASM builds.
// These mocks allow IDE support, compilation, and unit testing on non-WASM platforms.
// Plugin authors can use the exported mock instances to set expectations in tests.
//
//go:build !wasip1

package host

import (
	"github.com/stretchr/testify/mock"
)

// FingerprintRequest represents the FingerprintRequest data structure.
// FingerprintRequest identifies the library-relative file to fingerprint.
type FingerprintRequest struct {
	LibraryID int32  `json:"libraryId"`
	Path      string `json:"path"`
}

// FingerprintResponse represents the FingerprintResponse data structure.
// FingerprintResponse contains the computed Chromaprint fingerprint.
type FingerprintResponse struct {
	Fingerprint string `json:"fingerprint"`
	DurationMs  int64  `json:"durationMs"`
}

// mockFingerprintService is the mock implementation for testing.
type mockFingerprintService struct {
	mock.Mock
}

// FingerprintMock is the auto-instantiated mock instance for testing.
// Use this to set expectations: host.FingerprintMock.On("MethodName", args...).Return(values...)
var FingerprintMock = &mockFingerprintService{}

// Compute is the mock method for FingerprintCompute.
func (m *mockFingerprintService) Compute(request FingerprintRequest) (*FingerprintResponse, error) {
	args := m.Called(request)
	return args.Get(0).(*FingerprintResponse), args.Error(1)
}

// FingerprintCompute delegates to the mock instance.
// Compute runs fpcalc on the given library-relative file and returns its fingerprint.
func FingerprintCompute(request FingerprintRequest) (*FingerprintResponse, error) {
	return FingerprintMock.Compute(request)
}
