// Code generated by ndpgen. DO NOT EDIT.
//
// This file contains client wrappers for the SpeechMusicDetect host service.
// It is intended for use in Navidrome plugins built with TinyGo.
//
//go:build wasip1

package host

import (
	"encoding/json"
	"errors"

	"github.com/navidrome/navidrome/plugins/pdk/go/pdk"
)

// SpeechMusicDetectRequest represents the SpeechMusicDetectRequest data structure.
// SpeechMusicDetectRequest identifies the library-relative file to analyze.
type SpeechMusicDetectRequest struct {
	LibraryID int32  `json:"libraryId"`
	Path      string `json:"path"`
}

// SpeechMusicDetectResponse represents the SpeechMusicDetectResponse data structure.
// SpeechMusicDetectResponse contains the labeled segments inaSpeechSegmenter found in the file,
// in chronological order.
type SpeechMusicDetectResponse struct {
	Segments []SpeechMusicSegment `json:"segments"`
}

// SpeechMusicSegment represents the SpeechMusicSegment data structure.
// SpeechMusicSegment is a labeled span of a track, in milliseconds, as classified by
// inaSpeechSegmenter. Label is one of "speech", "music", "noEnergy" (silence), or "noise".
type SpeechMusicSegment struct {
	Label   string `json:"label"`
	StartMs int64  `json:"startMs"`
	EndMs   int64  `json:"endMs"`
}

// speechmusicdetect_detect is the host function provided by Navidrome.
//
//go:wasmimport extism:host/user speechmusicdetect_detect
func speechmusicdetect_detect(uint64) uint64

type speechMusicDetectDetectRequest struct {
	Request SpeechMusicDetectRequest `json:"request"`
}

type speechMusicDetectDetectResponse struct {
	Result *SpeechMusicDetectResponse `json:"result,omitempty"`
	Error  string                     `json:"error,omitempty"`
}

// SpeechMusicDetectDetect calls the speechmusicdetect_detect host function.
// Detect runs inaSpeechSegmenter on the given library-relative file and returns its
// labeled segments.
func SpeechMusicDetectDetect(request SpeechMusicDetectRequest) (*SpeechMusicDetectResponse, error) {
	// Marshal request to JSON
	req := speechMusicDetectDetectRequest{
		Request: request,
	}
	reqBytes, err := json.Marshal(req)
	if err != nil {
		return nil, err
	}
	reqMem := pdk.AllocateBytes(reqBytes)
	defer reqMem.Free()

	// Call the host function
	responsePtr := speechmusicdetect_detect(reqMem.Offset())

	// Read the response from memory
	responseMem := pdk.FindMemory(responsePtr)
	responseBytes := responseMem.ReadBytes()

	// Parse the response
	var response speechMusicDetectDetectResponse
	if err := json.Unmarshal(responseBytes, &response); err != nil {
		return nil, err
	}

	// Convert Error field to Go error
	if response.Error != "" {
		return nil, errors.New(response.Error)
	}

	return response.Result, nil
}
