// Code generated by ndpgen. DO NOT EDIT.
//
// This file contains mock implementations for non-WASM builds.
// These mocks allow IDE support, compilation, and unit testing on non-WASM platforms.
// Plugin authors can use the exported mock instances to set expectations in tests.
//
//go:build !wasip1

package host

import (
	"github.com/stretchr/testify/mock"
)

// SilenceDetectRequest represents the SilenceDetectRequest data structure.
// SilenceDetectRequest identifies the library-relative file to analyze and the ffmpeg
// silencedetect thresholds to use.
type SilenceDetectRequest struct {
	LibraryID  int32   `json:"libraryId"`
	Path       string  `json:"path"`
	NoiseDB    float32 `json:"noiseDb"`
	DurationMs int32   `json:"durationMs"`
}

// SilenceDetectResponse represents the SilenceDetectResponse data structure.
// SilenceDetectResponse contains the spans of silence ffmpeg found in the file.
type SilenceDetectResponse struct {
	Spans []SilenceSpan `json:"spans"`
}

// SilenceSpan represents the SilenceSpan data structure.
// SilenceSpan is a detected span of silence within a track, in milliseconds.
type SilenceSpan struct {
	StartMs int64 `json:"startMs"`
	EndMs   int64 `json:"endMs"`
}

// mockSilenceDetectService is the mock implementation for testing.
type mockSilenceDetectService struct {
	mock.Mock
}

// SilenceDetectMock is the auto-instantiated mock instance for testing.
// Use this to set expectations: host.SilenceDetectMock.On("MethodName", args...).Return(values...)
var SilenceDetectMock = &mockSilenceDetectService{}

// Detect is the mock method for SilenceDetectDetect.
func (m *mockSilenceDetectService) Detect(request SilenceDetectRequest) (*SilenceDetectResponse, error) {
	args := m.Called(request)
	return args.Get(0).(*SilenceDetectResponse), args.Error(1)
}

// SilenceDetectDetect delegates to the mock instance.
// Detect runs ffmpeg silencedetect on the given library-relative file and returns the
// detected silence spans.
func SilenceDetectDetect(request SilenceDetectRequest) (*SilenceDetectResponse, error) {
	return SilenceDetectMock.Detect(request)
}
